### ISSUE TITLE
QGIS plugin not running  No module sicpy

### ISSUE THREAD

**Issue by edblanch** [JMG30/flight_planner#10]
I am running QGIS 3.24 and Python 3.8 when I try to run the flight planner plugin QGIS says no module scpy.

**Comment by rhurlin** [comment]
Hi @edblanch, do you mean scipy instead of sicpy?

SciPy seems to be needed or multidimensional image processing because of its `scipy.ndimage` package f(see worker.py and functions.py in flight_planner). You could try installing **Python's module SciPy** and see what happens ...

Hopefully someone who knows more about this has a better answer ;)

**Comment by JMG30** [comment]
I've downloaded QGIS 3.24 and everything works fine. I didn't notice error with scipy module or any other bug.

@edblanch did you try to restart QGIS?

**Comment by StevePirateX** [comment]
It works fine for me with version 3.24 of QGIS but I'm on Python 3.10.5. I do have scipy installed. You might just need to open a terminal and run `pip install scipy`. You can check it's installed by checking it's version `python -c "import scipy; scipy.__version__"`. This will print out the version of scipy.
