### ISSUE TITLE
Can't edit flight control section.

### ISSUE THREAD

**Issue by subhadipghorui** [JMG30/flight_planner#7]
Please if anybody has step by step guide, help me.

**Comment by JMG30** [comment]
In order to be able to do anything in the flight control section, you must first enter a DTM (this is necessary - I usually work with the DTM from SRTM, but you can provide your own). Then you need to provide the vector layer of the projection centres points with the External Orientation parameters (Altitude Above Sea Level [meters] and Omega, Phi and Kappa angles (degrees) - all fields in attribute table must be numeric type. X, Y are derived by location of points in layer - this is why you not point them out manually. Don't forget about camera parameters in right upper corner of GUI!

Then you can get 3 products:
1. Vector layer representig footprint of all photos. It is calculated in an iterative approach, so you can set iteration threshold - calculating wil be completed if distance between all vertices of ith and i-1 iteration is smaller than the threshold :).
2. Logical sum of overlapping photos - it's more readable (in my opinion) version of 1st product, but less accurate (beacuse it's raster).
3. GSD map - raster layer representing Ground Sampling Distance.

Then just click Accept button (the one at the very bottom).

And last but not least. Current version of plugin is veeeery slow, so if you want to do calculation a little bit faster clip the DTM to smallest possible (but still covering neccesary area) range. The bigger size of DTM and the better resolution DTM is, the slower plugin works. I'm working now at new version of plugin, that will be faster and have less confusing GUI (I hope so).

If anything is not clear, feel free to ask.
