### ISSUE TITLE
Error: CRS of layer cannot be geographic

### ISSUE THREAD

**Issue by malabrito** [JMG30/flight_planner#9]
Starting using QGIS after several years for the purpose of photogrammetry workflow, so apologizes if I didn't get something obvious. 

I created a polygon shapefile (New Shapefile Layer), with CRS set to WGS84.

When I select this shapefile as AoI, I get the error message: CRS of layer cannot be geographic.

What I am getting wrong?

**Comment by JMG30** [comment]
I made it on purpose. To do the project the plugin needs to calculate "width" / "height" of the AoI, then divide, multiply it etc etc and it was much easier for me to implemented it and operated only in metric values (especially that camera parameters and GSD are also in metric system) and don't mix everything with degrees (like WGS84). That's why I force a user to don't use geographic CRS with degrees. I know it's not convenient for the user, but sometimes I just wanted to simplify my work.

So the solution is making AoI in metric CRS and then (if you want it) to export results to WGS84.

**Comment by malabrito** [comment]
Ah I see. 

And how do I create a metric CSR polygon in QGIS?

Many thanks

**Comment by JMG30** [comment]
Just choose CRS with "+units=m" in Proj4 when you create/export existing shapefile like in example below.

![obraz](https://user-images.githubusercontent.com/44444960/125156208-a1a73080-e164-11eb-98eb-a81869afa9ab.png)

**Comment by malabrito** [comment]
Thank you!
Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: JMG30 ***@***.***>
Enviado: sábado, julho 10, 2021 4:54 AM
Para: JMG30/flight_planner
Cc: Matheus Brito; Author
Assunto: Re: [JMG30/flight_planner] Error: CRS of layer cannot be geographic (#9)


Just choose CRS with "+units=m" in Proj4 when you create/export existing shapefile like in example below.

[obraz]<https://user-images.githubusercontent.com/44444960/125156208-a1a73080-e164-11eb-98eb-a81869afa9ab.png>
